### PR TITLE
Hex numbers in upper case. 

### PR DESCRIPTION
**Pull request by lemire**
Fix for https://github.com/piotte13/SIMD-Visualiser/issues/18

### CODE REVIEW

**Comment by piotte13** [comment]
Instead of doing the same operations in every file, I think we  should have a class that handles the visual representation of the number.

Ex: add a class in the folder Utils that has a function getVisualString(number).

With such a function, we can also handle whether we want to use hex or decimals. Everything done in a centralized place.

**Comment by lemire** [comment]
Sure. If you look at ny code comments from earlier PR you’ll notice that I flagged other functions for similar refactoring. 

Ideally we’d like to have "vectors" be smarter. So you should be able to change how you represent it smartly.

So far my code changes are functional and narrow but a bit hackish. We need to do better.

I think that’s a distinct issue.

**Comment by lemire** [comment]
That is, I deliberately chose not to be clever.

**Comment by lemire** [comment]
Let me be clearer. I think we should be able to tell a vector how we want it to print out (e.g. as a series of float, as signed 32-bit ints, as unsigned 32-bit ints, as hex 32-bitvints). And we should even move the "change how you are represented" animation off the instruction classes.

Look at my animation code... it is too complicated!

**Comment by lemire** [comment]
We need to make it easier to add new instructions... currently it is too much code!

**Comment by piotte13** [comment]
I agree 100%.  It was something I had in mind, but didn't have the time to implement.  Since the project will be growing fast from now, I think it should be among our top priorities.

**Comment by lemire** [comment]
Right. I think it useful strategically to be progressively clever... that is now that you see my code, it is easy to reason about how to make it nicer... without falling in the over engineering trap.

**Pull request merged**
